EBI-G2P/gene2phenotype_web

- src/router/index.js
- src/views/DiseaseView.vue
[G2P-79](https://www.ebi.ac.uk/panda/jira/browse/G2P-79)
> Adding disease page

- src/components/header/Header.vue
- src/components/header/HeaderWithoutSearch.vue
- src/router/index.js
- src/views/DiseaseView.vue
- src/views/ListCurationView.vue
[G2P-123](https://www.ebi.ac.uk/panda/jira/browse/G2P-123)
> List Curation Entries

- package-lock.json
- package.json
- src/App.vue
- src/components/chart/BarChart.vue
- src/components/header/Header.vue
- src/components/header/HeaderWithoutSearch.vue
- src/main.js
- src/router/index.js
- src/views/AboutProjectView.vue
- src/views/DiseaseView.vue
- src/views/GeneView.vue
- src/views/HomePageView.vue
- src/views/ListCurationView.vue
- src/views/LocusGeneDiseaseView.vue
- src/views/PanelView.vue
- src/views/SearchPageView.vue
This PR includes the following changes:
Implement Search functionality
Add Panel page
Add LocusGeneDisease page
Update Gene page
Update About Project page
Update HeaderWithoutSearch component
Minor change in App component
> Add new Pages, Implement Search, and improve existing pages

- src/views/LocusGeneDiseaseView.vue
[G2P-145](https://www.ebi.ac.uk/panda/jira/browse/G2P-145)
> G2P-145 - Phenotypes table

- src/components/curation/ClinicalPhenotype.vue
- src/components/curation/Mechanism.vue
- src/components/footer/Footer.vue
- src/components/header/Header.vue
- src/components/header/HeaderWithoutSearch.vue
- src/router/index.js
- src/utility/CurationConstants.js
- src/utility/CurationUtility.js
- src/views/AboutProjectView.vue
- src/views/CuratorsView.vue
- src/views/DisclaimerView.vue
- src/views/HomePageView.vue
- src/views/LocusGeneDiseaseView.vue
- src/views/PanelView.vue
Code changes for Jira tasks G2P-167, G2P-169 and other changes
> New pages and other changes

- src/components/curation/AlertModal.vue
- src/components/curation/ClinicalPhenotype.vue
- src/components/curation/Disease.vue
- src/components/curation/Publication.vue
- src/components/curation/SaveSuccessAlert.vue
- src/components/header/Header.vue
- src/components/header/HeaderWithoutSearch.vue
- src/router/index.js
- src/utility/CurationUtility.js
- src/views/AddLocusGeneDiseaseView.vue
- src/views/ListCurationView.vue
- src/views/UpdateLocusGeneDiseaseView.vue
- src/views/VariantFilteringView.vue
This PR includes changes for the Jira tasks [G2P-188](https://www.ebi.ac.uk/panda/jira/browse/G2P-188), [G2P-191](https://www.ebi.ac.uk/panda/jira/browse/G2P-191), [G2P-171](https://www.ebi.ac.uk/panda/jira/browse/G2P-171) and other fixes/improvements in add g2p record page and update draft g2p record page.
> HPO terms input, display warning popups, Variant filtering page and other fixes

- src/components/footer/Footer.vue
- src/components/header/Header.vue
- src/components/header/HeaderWithoutSearch.vue
- src/router/index.js
- src/views/DataDownloadView.vue
Changes related to Jira task [G2P-166](https://www.ebi.ac.uk/panda/jira/browse/G2P-166)
> G2P data download page

- src/components/curation/Publication.vue
- src/components/curation/PublishSuccessAlert.vue
- src/components/curation/SaveNotPublishSuccessAlert.vue
- src/views/AddLocusGeneDiseaseView.vue
- src/views/HomePageView.vue
- src/views/PanelView.vue
- src/views/UpdateLocusGeneDiseaseView.vue
Changes related to Jira task - [G2P-218](https://www.ebi.ac.uk/panda/jira/browse/G2P-218)
> Improvements to save and publish

- src/components/alert/LoginErrorAlert.vue
- src/components/curation/GeneInformation.vue
- src/components/header/Header.vue
- src/components/header/HeaderWithoutSearch.vue
- src/router/index.js
- src/utility/AuthenticationUtility.js
- src/views/AddLocusGeneDiseaseView.vue
- src/views/DataDownloadView.vue
- src/views/DiseaseView.vue
- src/views/GeneView.vue
- src/views/HomePageView.vue
- src/views/ListCurationView.vue
- src/views/LocusGeneDiseaseView.vue
- src/views/LoginView.vue
- src/views/PanelView.vue
- src/views/SearchPageView.vue
- src/views/UpdateLocusGeneDiseaseView.vue
Changes related to Jira task: [G2P-205](https://www.ebi.ac.uk/panda/jira/browse/G2P-205)
> Authentication for website

- src/components/curation/Confidence.vue
- src/components/curation/Disease.vue
- src/components/curation/Genotype.vue
- src/components/curation/Mechanism.vue
- src/components/curation/Panel.vue
- src/components/curation/Publication.vue
- src/components/curation/SaveNotPublishSuccessAlert.vue
- src/router/index.js
- src/views/AddLocusGeneDiseaseView.vue
- src/views/ListCurationView.vue
- src/views/UpdateLocusGeneDiseaseView.vue
Code changes related to Jira tasks - [G2P-207](https://www.ebi.ac.uk/panda/jira/browse/G2P-207) and [G2P-252](https://www.ebi.ac.uk/panda/jira/browse/G2P-252)
> Code changes for G2P-207 and G2P-252

- src/router/index.js
- src/views/LocusGeneDiseaseView.vue
- src/views/UpdateRecordView.vue
- src/views/update/AddPanelModal.vue
- src/views/update/UpdateConfidence.vue
- src/views/update/UpdatePanel.vue
For published records, these code changes provide functionalities to add record to panel and update confidence of record.
Code changes related to Jira tasks: [G2P-85](https://www.ebi.ac.uk/panda/jira/browse/G2P-85), [G2P-238](https://www.ebi.ac.uk/panda/jira/browse/G2P-238)
> Add record to panel and update confidence of record

- src/components/curation/Mechanism.vue
- src/views/AddLocusGeneDiseaseView.vue
- src/views/UpdateLocusGeneDiseaseView.vue
Adding the Badonyi probabilities et al to the curation form
> Adding Marsh probabilities to curation form

- src/components/curation/VariantTypes.vue
- src/components/footer/Footer.vue
- src/views/AboutProjectView.vue
- src/views/CuratorsView.vue
- src/views/DiseaseView.vue
- src/views/PublicationsView.vue
- src/views/VariantFilteringView.vue
Code changes related to Jira Task [G2P-262](https://www.ebi.ac.uk/panda/jira/browse/G2P-262)
> G2p 262 feedback changes

- src/utility/CommonUtility.js
- src/views/LocusGeneDiseaseView.vue
Code changes related to the following Jira tasks:
1. [G2P-256](https://www.ebi.ac.uk/panda/jira/browse/G2P-256)
2. [G2P-257](https://www.ebi.ac.uk/panda/jira/browse/G2P-257)
3. [G2P-258](https://www.ebi.ac.uk/panda/jira/browse/G2P-258)
4. [G2P-279](https://www.ebi.ac.uk/panda/jira/browse/G2P-279)
5. [G2P-283](https://www.ebi.ac.uk/panda/jira/browse/G2P-283)
6. [G2P-284](https://www.ebi.ac.uk/panda/jira/browse/G2P-284)
7. [G2P-285](https://www.ebi.ac.uk/panda/jira/browse/G2P-285)
8. [G2P-286](https://www.ebi.ac.uk/panda/jira/browse/G2P-286)
> update LGD record page to display more record data fields

- src/components/curation/Mechanism.vue
- src/components/curation/VariantConsequences.vue
- src/views/GeneView.vue
- src/views/LocusGeneDiseaseView.vue
- src/views/PanelView.vue
- src/views/update/AddPanelModal.vue
Code changes related to [G2P-287](https://www.ebi.ac.uk/panda/jira/browse/G2P-287), [G2P-295](https://www.ebi.ac.uk/panda/jira/browse/G2P-295), [G2P-301](https://www.ebi.ac.uk/panda/jira/browse/G2P-301), and [G2P-305](https://www.ebi.ac.uk/panda/jira/browse/G2P-305)
> Changes for G2P-287, 295, 301, 305

- src/views/LocusGeneDiseaseView.vue
- src/views/SearchPageView.vue
Requires [API-PR 42](https://github.com/EBI-G2P/gene2phenotype_api/pull/42) to be merged first
> Changes based on molecular mechanism search changes

- src/views/DataDownloadView.vue
- src/views/HomePageView.vue
- src/views/PanelView.vue
Changes related to Jira task: [G2P-300](https://www.ebi.ac.uk/panda/jira/browse/G2P-300)
> Change panel data download format

- src/components/header/Header.vue
- src/components/header/HeaderWithoutSearch.vue
- src/views/DataDownloadView.vue
- src/views/HomePageView.vue
Set Cache-Control header with "no-cache" value for panel api calls
> Set Cache-Control header for panel api calls

- src/views/HomePageView.vue
Changes related to Jira task: [G2P-250](https://www.ebi.ac.uk/panda/jira/browse/G2P-250)
> Change search examples styling and text in Homepage

- src/views/SearchPageView.vue
Code changes related to Jira task: [G2P-313](https://www.ebi.ac.uk/panda/jira/browse/G2P-313)
> In search page, display confidence in search results table

- src/views/LocusGeneDiseaseView.vue
Adding the list of curators to the lgd page
> Changes to add the curator list

- src/components/curation/ClinicalPhenotype.vue
- src/views/AddLocusGeneDiseaseView.vue
- src/views/UpdateLocusGeneDiseaseView.vue
How to test -
Search a phenotype on the search phenotype box, results start to show from >3 letters 
On selection: 
- Populates the HPO terms with the HPO term id (separated by ";" ) 
- Table showing the selected HPO term and accession 
- Summary is still comments, curator decide to put in 
The phenotype object in the this.input then looks the same as before. 
Thank you 
Ola
> Changes for autocomplete dropdown

- src/utility/Constants.js
- src/utility/UrlConstants.js
- src/views/GeneView.vue
- src/views/LocusGeneDiseaseView.vue
- src/views/PanelView.vue
- src/views/SearchPageView.vue
- src/views/TerminologyView.vue
- src/views/UpdateRecordView.vue
- src/views/update/UpdateMechanism.vue
This PR includes following changes:
- Allow mechanism to be updated for published G2P records [G2P-290](https://www.ebi.ac.uk/panda/jira/browse/G2P-290)
- Create common constant for confidence level to color mapping (code improvement)
- Change display of confidence level in lgd record page
> Allow mechanism to be updated for published G2P records and other improvements

- src/views/SearchPageView.vue
Ticket: [G2P-331](https://www.ebi.ac.uk/panda/jira/browse/G2P-331)
> Update search to return total number of results

- src/views/PublicationsView.vue
Ticket: [G2P-326](https://www.ebi.ac.uk/panda/jira/browse/G2P-326)
> Update curation publication

- src/components/curation/ExistingGeneInformation.vue
- src/components/header/Header.vue
- src/components/header/HeaderWithoutSearch.vue
- src/utility/AuthenticationUtility.js
- src/views/AddLocusGeneDiseaseView.vue
- src/views/LoginView.vue
Code changes related to [G2P-276](https://www.ebi.ac.uk/panda/jira/browse/G2P-276)
> Search and display existing gene drafts and records in Add new G2P record page

- src/components/curation/GeneInformation.vue
- src/utility/Constants.js
- src/views/GeneView.vue
Ticket: [G2P-312](https://www.ebi.ac.uk/panda/jira/browse/G2P-312)
> Add "Show more" to long gene functions

- src/components/curation/MechanismEvidence.vue
- src/utility/CurationConstants.js
- src/views/LocusGeneDiseaseView.vue
- src/views/update/UpdateMechanism.vue
Code changes related to Jira Tasks [G2P-334](https://www.ebi.ac.uk/panda/jira/browse/G2P-334), [G2P-335](https://www.ebi.ac.uk/panda/jira/browse/G2P-335)
> Code changes for G2P 334 335

- src/views/DiseaseView.vue
Add gene and confidence to `latest records`.
> Update disease page

- src/components/curation/Confidence.vue
- src/utility/CurationConstants.js
- src/views/update/UpdateConfidence.vue
[G2P-342](https://www.ebi.ac.uk/panda/jira/browse/G2P-342)
> Updating the curation interface update to reorder level

- src/components/curation/Disease.vue
- src/components/curation/ExistingGeneInformation.vue
- src/components/curation/GeneInformation.vue
- src/components/curation/Publication.vue
- src/components/header/Header.vue
- src/components/header/HeaderWithoutSearch.vue
- src/components/tooltip/ToolTip.vue
- src/views/AboutProjectView.vue
- src/views/DisclaimerView.vue
- src/views/DiseaseView.vue
- src/views/GeneView.vue
- src/views/LocusGeneDiseaseView.vue
- src/views/PanelView.vue
- src/views/ProfileView.vue
- src/views/PublicationsView.vue
- src/views/SearchPageView.vue
- src/views/VariantFilteringView.vue
- src/views/update/UpdateConfidence.vue
- src/views/update/UpdateMechanism.vue
- src/views/update/UpdatePanel.vue
Code changes related to [G2P-330](https://www.ebi.ac.uk/panda/jira/browse/G2P-330), [G2P-339](https://www.ebi.ac.uk/panda/jira/browse/G2P-339) and other code improvements
> Changes to About project page, Disclaimer page, Search page, and other code improvements

- src/views/AddLocusGeneDiseaseView.vue
- src/views/UpdateLocusGeneDiseaseView.vue
Code change related to [G2P-350](https://www.ebi.ac.uk/panda/jira/browse/G2P-350)
> G2P-350 - Show alert before leaving curation form

- src/views/TerminologyView.vue
[G2P-327](https://www.ebi.ac.uk/panda/jira/browse/G2P-327)
> Website changes for terminology updates

- src/views/DiseaseView.vue
- src/views/GeneView.vue
- src/views/LocusGeneDiseaseView.vue
- src/views/PanelView.vue
Update Disease, Gene, Panel and LGD record pages based on mechanism api response change. Code change related to [G2P-353](https://www.ebi.ac.uk/panda/jira/browse/G2P-353)
> Update Disease, Gene, Panel, LGD record pages based on mechanism changes

- src/components/add-publication/AddPublication.vue
- src/components/add-publication/UpdateMechanismEvidence.vue
- src/components/curation/MechanismEvidence.vue
- src/components/update-record/UpdateMechanism.vue
- src/router/index.js
- src/utility/AddPublicationUtility.js
- src/utility/CurationUtility.js
- src/views/AddLocusGeneDiseaseView.vue
- src/views/NotFoundView.vue
- src/views/UpdateLocusGeneDiseaseView.vue
- src/views/UpdateRecordView.vue
Make changes to mechanism section in Add publication page and update mechanism section in update record page. Code changes related to [G2P-353](https://www.ebi.ac.uk/panda/jira/browse/G2P-353) and [G2P-359](https://www.ebi.ac.uk/panda/jira/browse/G2P-359). Also, created 404 error page and other improvements.
> Make changes to mechanism sections

- src/components/add-publication/UpdateVariantTypes.vue
- src/views/GeneView.vue
- src/views/LocusGeneDiseaseView.vue
This PR has [G2P-429](https://www.ebi.ac.uk/panda/jira/browse/G2P-429) related changes and external links text changes in Gene page.
> G2P-429 related changes and text changes in Gene page

- src/views/UpdateLocusGeneDiseaseView.vue
Code changes related to [G2P-414](https://www.ebi.ac.uk/panda/jira/browse/G2P-414) - In update new g2p record draft page, if any duplicate publication is being added then display error.
> G2P 414 - Changes in update new g2p record draft page

- src/components/add-publication/AddPublication.vue
- src/views/AddLocusGeneDiseaseView.vue
- src/views/UpdateLocusGeneDiseaseView.vue
Improve publication input validations based on review comments in PR https://github.com/EBI-G2P/gene2phenotype_web/pull/89
> G2P-414 - Improve publication input validations

- src/views/AboutProjectView.vue
- src/views/DiseaseView.vue
- src/views/GeneView.vue
- src/views/HomePageView.vue
- src/views/PanelView.vue
[G2P-323](https://www.ebi.ac.uk/panda/jira/browse/G2P-323), [G2P-336](https://www.ebi.ac.uk/panda/jira/browse/G2P-336), [G2P-380](https://www.ebi.ac.uk/panda/jira/browse/G2P-380), [G2P-421](https://www.ebi.ac.uk/panda/jira/browse/G2P-421) related changes and other minor text changes
> G2P-323,336,380,421 related changes and other minor text changes

- src/views/DataDownloadView.vue
- src/views/VariantFilteringView.vue
[G2P-289](https://www.ebi.ac.uk/panda/jira/browse/G2P-289)
> Adding changes for FTP organization

- src/components/curation/ExistingGeneInformation.vue
- src/components/update-record/AddComment.vue
- src/utility/UrlConstants.js
- src/views/DiseaseView.vue
- src/views/GeneView.vue
- src/views/ListCurationView.vue
- src/views/SearchPageView.vue
- src/views/UpdateRecordView.vue
This PR includes changes for [G2P-365](https://www.ebi.ac.uk/panda/jira/browse/G2P-365), minor text changes in table headers, and code improvements.
> G2P-365 related changes and other improvements

- src/components/footer/Footer.vue
- src/components/header/Header.vue
- src/components/header/HeaderWithoutSearch.vue
- src/router/index.js
- src/utility/UrlConstants.js
- src/views/ReferenceDataView.vue
Code changes related to [G2P-390](https://www.ebi.ac.uk/panda/jira/browse/G2P-390).
> G2P-390 - G2P reference data page

- src/components/add-publication/UpdateMechanismEvidence.vue
- src/components/add-publication/UpdatePublication.vue
- src/components/curation/Mechanism.vue
- src/components/curation/Publication.vue
- src/components/update-record/UpdateMechanism.vue
- src/utility/CurationUtility.js
This PR includes the following changes:
1. Mechanism and Categorisation input validations in Curation form, Update record page and Add publications page [G2P-383](https://www.ebi.ac.uk/panda/jira/browse/G2P-383)
2. Publication families and affected individuals input validations in Curation form and Add publications page [G2P-275](https://www.ebi.ac.uk/panda/jira/browse/G2P-275)
> Publication, Mechanism and Categorisation input validations

- src/components/curation/GeneInformation.vue
Code change related to [G2P-461](https://www.ebi.ac.uk/panda/jira/browse/G2P-461)
> G2P-461 - Update ensembl URL

- src/components/update-record/UpdatePhenotype.vue
- src/components/update-record/UpdateVariantConsequences.vue
- src/components/update-record/UpdateVariantTypes.vue
- src/utility/UrlConstants.js
- src/views/UpdateRecordView.vue
Code changes related to [G2P-434](https://www.ebi.ac.uk/panda/jira/browse/G2P-434)
> G2P-434 - Add phenotypes, variant types, consequences to published records

- src/utility/AddPublicationUtility.js
- src/utility/CurationUtility.js
Code changes related to [G2P-472](https://www.ebi.ac.uk/panda/jira/browse/G2P-472). In curation form and add publications page, support adding phenotypic summary without selecting hpo terms.
> G2P-472 - Support adding phenotypic summary without selecting hpo terms

- src/components/add-publication/AddPublication.vue
- src/components/modal/AddPanelModal.vue
- src/components/update-record/UpdatePanel.vue
- src/utility/ErrorUtility.js
- src/views/AddLocusGeneDiseaseView.vue
- src/views/SearchPageView.vue
- src/views/UpdateLocusGeneDiseaseView.vue
Code changes related to [G2P-474](https://www.ebi.ac.uk/panda/jira/browse/G2P-474).
> G2P-474 - Changes related to display of api error msg

- src/utility/Constants.js
- src/views/PanelView.vue
Ticket: [G2P-340](https://www.ebi.ac.uk/panda/jira/browse/G2P-340)
> Remove curators list from panel page

- src/components/curation/Disease.vue
- src/components/modal/DeleteCrossReferenceModal.vue
- src/components/update-record/UpdateDisease.vue
- src/services/api.js
- src/utility/Constants.js
- src/utility/UrlConstants.js
- src/views/UpdateRecordView.vue
Code changes related to [G2P-438](https://www.ebi.ac.uk/panda/jira/browse/G2P-438)
> G2P-438 - Add/Delete cross references for existing records

- src/components/add-publication/UpdatePhenotype.vue
- src/components/add-publication/UpdateVariantTypes.vue
- src/components/curation/ClinicalPhenotype.vue
- src/components/curation/Confidence.vue
- src/components/curation/ExistingGeneInformation.vue
- src/components/curation/GeneInformation.vue
- src/components/curation/Mechanism.vue
- src/components/curation/MechanismEvidence.vue
- src/components/curation/VariantTypes.vue
- src/components/update-record/UpdatePhenotype.vue
- src/utility/AddPublicationUtility.js
- src/utility/CurationUtility.js
- src/views/AddLocusGeneDiseaseView.vue
- src/views/DiseaseView.vue
- src/views/GeneView.vue
- src/views/ListCurationView.vue
- src/views/LocusGeneDiseaseView.vue
- src/views/PanelView.vue
- src/views/ProfileView.vue
- src/views/ReferenceDataView.vue
- src/views/SearchPageView.vue
- src/views/TerminologyView.vue
- src/views/UpdateLocusGeneDiseaseView.vue
Code changes related to [G2P-502](https://www.ebi.ac.uk/panda/jira/browse/G2P-502), add link to GenCC on gene page, and below code improvements.
1. Standardise imports
2. Directly use constants instead of assinging them to other variables
> G2P-502 - Add external links and code improvements

- src/components/curation/Mechanism.vue
- src/components/curation/MechanismEvidence.vue
- src/components/update-record/UpdateMechanism.vue
- src/utility/AddPublicationUtility.js
- src/utility/CurationUtility.js
- src/views/AddLocusGeneDiseaseView.vue
- src/views/UpdateLocusGeneDiseaseView.vue
Code changes related to [G2P-456](https://www.ebi.ac.uk/panda/jira/browse/G2P-456).
> G2P-456 - Support multiple mechanism categorisations input in curation form

- src/components/curation/Confidence.vue
- src/components/update-record/UpdateConfidence.vue
- src/views/GeneView.vue
- src/views/SearchPageView.vue
Code changes related to G2P-467.  
On search page, for queries that have no g2p disease models, check if the query is a valid gene query and display its relevant gene page link.
Alos includes code improvement for sorting confidence category list.
> G2P-467 - Improve response on search page and code improvements

- src/components/footer/Footer.vue
- src/components/tooltip/ToolTip.vue
- src/router/index.js
Code changes related to [G2P-511](https://embl.atlassian.net/browse/G2P-511) and below improvements.
1. Small fix to custom scroll behaviour code
2. Set tooltip font size
> G2P-511 - Change privacy notice link in footer and other improvements

- src/views/SearchPageView.vue
On search page, improve display for different query types.
> On search page, improve display for different query types

- src/utility/CurationConstants.js
Change order of mechanism categorisations values.
---
[G2P-518](https://embl.atlassian.net/browse/G2P-518)
---
---
> G2P-518 - Change order of mechanism categorisations values

- src/components/add-publication/UpdateMechanismEvidence.vue
- src/components/curation/Mechanism.vue
- src/components/curation/MechanismEvidence.vue
- src/components/update-record/UpdateMechanism.vue
- src/utility/AddPublicationUtility.js
- src/utility/CurationUtility.js
- src/views/AddPublicationView.vue
Allow input for mechanism evidence regardless of mechanism support value in following pages:
1. Curation form (Add new g2p record page/ Update new g2p record draft page)
2. Add publications page (mechanism section)
3. Update g2p record page (mechanism section)
Also includes other minor improvements.
---
[G2P-447](https://embl.atlassian.net/browse/G2P-447)
---
---
> G2P 447 - Allow input for mechanism evidence regardless of mechanism support value

- src/components/update-record/UpdateDisease.vue
- src/utility/UrlConstants.js
- src/views/UpdateRecordView.vue
In update record page, support the addition of MONDO terms not linked to gene. Also, includes a minor improvement.
---
[G2P-384](https://embl.atlassian.net/browse/G2P-384)
---
---
> G2P-384 - In update record page, support the addition of MONDO terms not linked to gene

- README.md
- src/components/terminology/TerminologyDisplay.vue
1. In terminology page, add reference to Variant Consequence.
2. Update README
---
1. [G2P-549](https://embl.atlassian.net/browse/G2P-549)
3. [G2P-554](https://embl.atlassian.net/browse/G2P-554)
---
---
> G2P-549, 554 - Add reference to Variant Consequence in terminology page and update README

- src/App.vue
Add EMBL-EBI 2025 survey banner.
---
[G2P-553](https://embl.atlassian.net/browse/G2P-553)
---
---
> G2P-553 - Add EMBL-EBI 2025 survey banner

- src/components/update-record/UpdateReviewStatus.vue
- src/components/view-record/LocusGeneDiseaseDisplay.vue
- src/utility/UrlConstants.js
- src/views/UpdateRecordView.vue
Add option to update record review status on record update page and also for records under review, display "under review" flag on record page.
---
[G2P-564](https://embl.atlassian.net/browse/G2P-564)
---
---
> G2P-564 - Add option to update record review status

- src/components/add-publication/UpdatePublication.vue
- src/components/view-record/LocusGeneDiseaseDisplay.vue
Handle updated API response format for Publication individuals data.
---
[G2P-563](https://embl.atlassian.net/browse/G2P-563)
---
---
> G2P-563 - Handle updated API response format for Publication individuals data

- src/utility/CurationConstants.js
Update ontology term for non-coding variant.
---
[G2P-555](https://embl.atlassian.net/browse/G2P-555)
---
---
> G2P 555 - Update ontology term for non-coding variant

- src/components/footer/Footer.vue
- src/views/HomePageView.vue
Redesign homepage - move search box higher, redesign UI, and enhance responsiveness.
---
[G2P-536](https://embl.atlassian.net/browse/G2P-536)
---
---
> G2P 536 - Redesign homepage

- src/components/add-publication/UpdateMechanismEvidence.vue
- src/components/add-publication/UpdatePhenotype.vue
- src/components/add-publication/UpdatePublication.vue
- src/components/add-publication/UpdateVariantInformation.vue
- src/components/add-publication/UpdateVariantTypes.vue
- src/components/curation/Confidence.vue
- src/components/curation/Disease.vue
- src/components/curation/GeneInformation.vue
- src/components/curation/Publication.vue
- src/components/footer/Footer.vue
- src/components/header/Header.vue
- src/components/header/HeaderWithoutSearch.vue
- src/components/update-record/UpdateDisease.vue
- src/components/update-record/UpdateMechanism.vue
- src/components/update-record/UpdatePhenotype.vue
- src/components/update-record/UpdateVariantTypes.vue
- src/components/view-record/LocusGeneDiseaseDisplay.vue
- src/router/index.js
- src/utility/UrlConstants.js
- src/views/DiseaseView.vue
- src/views/GeneView.vue
- src/views/HelpView.vue
This PR includes the following changes:
1. Code improvements - Use external urls from constants file
2. Rename g2p website help page title, page link text, and url
---
Not applicable.
---
---
> Code improvements and rename changes related to g2p website help page

- package-lock.json
- package.json
Upgrade Axios to latest version v1.11.0
---
[G2P-582](https://embl.atlassian.net/browse/G2P-582)
---
---
> G2P-582 - Upgrade Axios to latest version

- src/App.vue
Remove EMBL-EBI 2025 survey banner.
---
[G2P-558](https://embl.atlassian.net/browse/G2P-558)
---
---
> G2P-558 - Remove EMBL-EBI 2025 survey banner

- src/components/view-record/LocusGeneDiseaseDisplay.vue
- src/utility/UrlConstants.js
This PR contains the following 2 changes in record page:
1. Expand publications section by default
2. Add link to view selected publications in EuropePMC
---
1. [G2P-527](https://embl.atlassian.net/browse/G2P-527)
3. [G2P-573](https://embl.atlassian.net/browse/G2P-573)
---
---
> G2P-527, 573 - View selected publications in EuropePMC and expand publications section

- src/components/add-publication/UpdatePublication.vue
- src/components/update-record/UpdateComment.vue
- src/components/update-record/UpdateMechanism.vue
- src/components/update-record/UpdatePhenotype.vue
- src/components/update-record/UpdateVariantTypes.vue
- src/components/view-record/LocusGeneDiseaseDisplay.vue
Improve the comments displayed on the record page.
---
[G2P-592](https://embl.atlassian.net/browse/G2P-592)
---
---
> Render comments text on record page

- src/views/ApiInformationView.vue
- src/views/DataDownloadView.vue
- Add API details on the download page https://wwwdev.ebi.ac.uk/gene2phenotype/download
- Update the API page with examples https://wwwdev.ebi.ac.uk/gene2phenotype/g2p-api-info
---
[G2P-454](https://embl.atlassian.net/browse/G2P-454)
---
---
> Add API details to download page

- src/components/code-block/CodeBlock.vue
- src/views/ApiInformationView.vue
- src/views/DataDownloadView.vue
In data download and g2p api info page, add code blocks with copy btn and other improvements
---
Not applicable.
---
---
> Updates to data download page and g2p api info page

- src/components/view-record/LocusGeneDiseaseDisplay.vue
In record page, add option to select/deselect all publications to view in EuropePMC
---
[G2P-611](https://embl.atlassian.net/browse/G2P-611)
---
---
> G2P-611 - In record page, add option to select/deselect all publications to view
